# Generated by Django 3.2.22 on 2023-12-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0003_task_sequential_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_hash',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
